services:
  product-db:
    image: postgres:16
    container_name: product-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdf
    ports:
      - "5435:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      - product-net

  product-service:
    build: .
    container_name: product-service
    environment:
      - PORT=8080
      - SPRING_R2DBC_URL=r2dbc:postgresql://product-db:5432/postgres?schema=product_schema
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=asdf
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_URL=jdbc:postgresql://product-db:5432/postgres?schema=product_schema
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=asdf
    ports:
      - "8080:8080"
    depends_on:
      - product-db
    networks:
      - product-net

volumes:
  product_data:

networks:
  product-net:
